# Generated by Django 2.2 on 2019-04-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='beachId',
            field=models.CharField(max_length=255),
        ),
    ]
