# Generated by Django 2.2 on 2019-04-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190421_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='beachId',
            field=models.TextField(),
        ),
    ]
