# Generated by Django 2.2 on 2019-04-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190421_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='beachId',
            new_name='beach_id',
        ),
    ]
