# Generated by Django 2.2 on 2019-04-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190421_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_username',
            field=models.CharField(default='joe', max_length=255),
        ),
    ]
