# Generated by Django 2.2 on 2019-04-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_author_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
    ]
